
export const lcData = [
  {
    id: 1,
    lcNumber: "LC-2023-001",
    status: "Active",
    openDate: "15/08/2023",
    dueDate: "15/11/2023",
    products: "Cotton Fabric, Polyester",
    quantity: "5000 yards",
    totalAmount: "$45,250.00",
    beneficiary: "ABC Textiles Ltd",

    basicInfo: {
      lcNumber: "LC-2023-001",
      lcType: "Sight LC",
      issueDate: "2023-08-15",
      expiryDate: "2023-11-15",
      lcValue: 45250,
      currency: "USD",
      status: "Active",
    },
    buyerInfo: {
      name: "John Smith",
      company: "Global Imports Inc.",
      address: "123 Trade Center, New York, NY 10001, USA",
      contactPerson: "Michael Johnson",
      phone: "+1 (555) 123-4567",
      email: "purchase@globalimports.com",
    },
    sellerInfo: {
      name: "ABC Textiles Owner",
      company: "ABC Textiles Ltd",
      address: "456 Textile Zone, Dhaka, Bangladesh",
      bankName: "Dutch Bangla Bank",
      accountNumber: "1234567890",
      swiftCode: "DBBLBDDHXXX",
      email: "info@abctextiles.com",
    },
    bankInfo: {
      issuingBank: "New York Commercial Bank",
      advisingBank: "Dutch Bangla Bank Main Branch",
      correspondentBank: "Standard Chartered Bank",
      swiftCode: "NYCBUS33",
      branch: "Main Branch",
      accountManager: "Sarah Williams",
      managerContact: "sarah.w@nycb.com",
    },
    shipmentInfo: {
      portOfLoading: "Chittagong Port, Bangladesh",
      portOfDischarge: "Port of New York, USA",
      shipmentDate: "2023-10-10",
      lastShipmentDate: "2023-10-20",
      transportType: "Sea Freight",
      shippingCompany: "Maersk Line",
      insurance: "All Risk Coverage by Sadharan Bima",
      incoterms: "FOB",
    },
    goodsInfo: [
      {
        productName: "Cotton Fabric",
        hsCode: "5208.11.00",
        quantity: 3000,
        unit: "YARDS",
        unitPrice: 12,
        totalValue: 36000,
        description: "Premium cotton fabric for garment manufacturing",
      },
      {
        productName: "Polyester Fabric",
        hsCode: "5407.52.00",
        quantity: 2000,
        unit: "YARDS",
        unitPrice: 4.625,
        totalValue: 9250,
        description: "High-quality polyester fabric",
      },
    ],
    paymentInfo: {
      terms: "At Sight",
      marginAmount: 9050,
      bankCharges: 300,
      commission: 450,
      dueDate: "2023-11-15",
      status: "Active",
      paidAmount: 0,
      paymentDate: "",
    },
    documentsRequired: [
      "Commercial Invoice",
      "Packing List",
      "Bill of Lading",
      "Insurance Certificate",
      "Certificate of Origin",
      "GSP Certificate",
    ],
    tracking: {
      status: "LC Opened",
      remarks: "LC opened successfully. Waiting for goods shipment.",
      attachments: [
        { name: "LC_Application.pdf", type: "PDF", size: "2.1 MB" },
        { name: "Proforma_Invoice.pdf", type: "PDF", size: "1.5 MB" },
      ],
      lastUpdated: "2023-08-15 10:30",
    },
  },

  {
    id: 2,
    lcNumber: "LC-2023-002",
    status: "Expired",
    openDate: "22/07/2023",
    dueDate: "22/10/2023",
    products: "Rice, Wheat",
    quantity: "2000 MT",
    totalAmount: "$125,800.00",
    beneficiary: "XYZ Trading Co",

    basicInfo: {
      lcNumber: "LC-2023-002",
      lcType: "Usance LC",
      issueDate: "2023-07-22",
      expiryDate: "2023-10-22",
      lcValue: 125800,
      currency: "USD",
      status: "Expired",
    },
    buyerInfo: {
      name: "Ahmed Hassan",
      company: "Bangladesh Food Corp.",
      address: "789 Commercial Area, Dhaka, Bangladesh",
      contactPerson: "Rahman Khan",
      phone: "+880 1712-345678",
      email: "procurement@bdfood.com",
    },
    sellerInfo: {
      name: "Rajesh Kumar",
      company: "XYZ Trading Co",
      address: "321 Grain Market, Mumbai, India",
      bankName: "State Bank of India",
      accountNumber: "9876543210",
      swiftCode: "SBININBBXXX",
      email: "export@xyztrading.com",
    },
    bankInfo: {
      issuingBank: "Sonali Bank Limited",
      advisingBank: "State Bank of India Mumbai",
      correspondentBank: "Citibank N.A.",
      swiftCode: "SONBBDDH",
      branch: "Motijheel Branch",
      accountManager: "Nasir Ahmed",
      managerContact: "nasir.a@sonalibank.com",
    },
    shipmentInfo: {
      portOfLoading: "Mumbai Port, India",
      portOfDischarge: "Chittagong Port, Bangladesh",
      shipmentDate: "2023-09-15",
      lastShipmentDate: "2023-09-25",
      transportType: "Sea Freight",
      shippingCompany: "CMA CGM",
      insurance: "Marine Insurance by Oriental Insurance",
      incoterms: "CIF",
    },
    goodsInfo: [
      {
        productName: "Basmati Rice",
        hsCode: "1006.30.00",
        quantity: 1000,
        unit: "MT",
        unitPrice: 85,
        totalValue: 85000,
        description: "Premium quality basmati rice",
      },
      {
        productName: "Wheat Flour",
        hsCode: "1101.00.00",
        quantity: 1000,
        unit: "MT",
        unitPrice: 40.8,
        totalValue: 40800,
        description: "High-grade wheat flour for commercial use",
      },
    ],
    paymentInfo: {
      terms: "90 Days after sight",
      marginAmount: 25160,
      bankCharges: 800,
      commission: 1258,
      dueDate: "2023-10-22",
      status: "Expired",
      paidAmount: 0,
      paymentDate: "",
    },
    documentsRequired: [
      "Commercial Invoice",
      "Packing List",
      "Bill of Lading",
      "Insurance Certificate",
      "Certificate of Origin",
      "Quality Certificate",
      "Phytosanitary Certificate",
    ],
    tracking: {
      status: "Expired - Unpaid",
      remarks: "LC expired without payment. Goods were not shipped on time.",
      attachments: [
        { name: "LC_Copy.pdf", type: "PDF", size: "2.8 MB" },
        { name: "Amendment_Request.pdf", type: "PDF", size: "1.2 MB" },
      ],
      lastUpdated: "2023-10-22 16:45",
    },
  },

  {
    id: 3,
    lcNumber: "LC-2023-003",
    status: "Pending",
    openDate: "10/09/2023",
    dueDate: "10/12/2023",
    products: "Electronics Components",
    quantity: "1500 units",
    totalAmount: "$89,600.00",
    beneficiary: "Tech Solutions Inc",

    // Detailed LC Info
    basicInfo: {
      lcNumber: "LC-2023-003",
      lcType: "Sight LC",
      issueDate: "2023-09-10",
      expiryDate: "2023-12-10",
      lcValue: 89600,
      currency: "USD",
      status: "Pending",
    },
    buyerInfo: {
      name: "Sarah Johnson",
      company: "Digital Electronics Ltd.",
      address: "555 Tech Park, California, USA",
      contactPerson: "Mark Wilson",
      phone: "+1 (555) 987-6543",
      email: "sourcing@digitalelectronics.com",
    },
    sellerInfo: {
      name: "Li Chen",
      company: "Tech Solutions Inc",
      address: "789 Innovation Hub, Shenzhen, China",
      bankName: "China Construction Bank",
      accountNumber: "6225880123456789",
      swiftCode: "PCBCCNBJSZX",
      email: "sales@techsolutions.com",
    },
    bankInfo: {
      issuingBank: "Bank of America",
      advisingBank: "China Construction Bank Shenzhen",
      correspondentBank: "HSBC Hong Kong",
      swiftCode: "BOFAUS3N",
      branch: "California Main Branch",
      accountManager: "Jennifer Davis",
      managerContact: "j.davis@bofa.com",
    },
    shipmentInfo: {
      portOfLoading: "Shenzhen Port, China",
      portOfDischarge: "Port of Los Angeles, USA",
      shipmentDate: "2023-11-15",
      lastShipmentDate: "2023-11-25",
      transportType: "Sea Freight",
      shippingCompany: "COSCO Shipping",
      insurance: "Cargo Insurance by Ping An",
      incoterms: "FOB",
    },
    goodsInfo: [
      {
        productName: "Microprocessors",
        hsCode: "8542.31.00",
        quantity: 800,
        unit: "PCS",
        unitPrice: 75,
        totalValue: 60000,
        description: "High-performance microprocessors",
      },
      {
        productName: "Memory Modules",
        hsCode: "8473.30.20",
        quantity: 700,
        unit: "PCS",
        unitPrice: 42.29,
        totalValue: 29600,
        description: "DDR4 memory modules for industrial use",
      },
    ],
    paymentInfo: {
      terms: "At Sight",
      marginAmount: 17920,
      bankCharges: 450,
      commission: 896,
      dueDate: "2023-12-10",
      status: "Pending",
      paidAmount: 0,
      paymentDate: "",
    },
    documentsRequired: [
      "Commercial Invoice",
      "Packing List",
      "Bill of Lading",
      "Insurance Certificate",
      "Certificate of Origin",
      "Test Certificate",
      "RoHS Certificate",
    ],
    tracking: {
      status: "Under Review",
      remarks:
        "Documents under bank verification. Waiting for compliance check.",
      attachments: [
        { name: "LC_Application.pdf", type: "PDF", size: "3.1 MB" },
        { name: "Technical_Specs.pdf", type: "PDF", size: "2.5 MB" },
        { name: "Compliance_Cert.pdf", type: "PDF", size: "1.8 MB" },
      ],
      lastUpdated: "2023-09-25 11:20",
    },
  },

  {
    // Basic LC Info
    id: 4,
    lcNumber: "LC-2023-004",
    status: "Active",
    openDate: "05/09/2023",
    dueDate: "05/01/2024",
    products: "Leather Goods",
    quantity: "800 pieces",
    totalAmount: "$32,400.00",
    beneficiary: "Premium Leather Co",

    basicInfo: {
      lcNumber: "LC-2023-004",
      lcType: "Sight LC",
      issueDate: "2023-09-05",
      expiryDate: "2024-01-05",
      lcValue: 32400,
      currency: "USD",
      status: "Active",
    },
    buyerInfo: {
      name: "Emma Thompson",
      company: "Fashion Boutique Chain",
      address: "777 Fashion Street, London, UK",
      contactPerson: "Oliver Brown",
      phone: "+44 20 7946 0958",
      email: "buying@fashionboutique.co.uk",
    },
    sellerInfo: {
      name: "Mohammad Karim",
      company: "Premium Leather Co",
      address: "123 Leather Street, Dhaka, Bangladesh",
      bankName: "Islami Bank Bangladesh",
      accountNumber: "20501234567890",
      swiftCode: "IBBLBDDH",
      email: "export@premiumleather.com",
    },
    bankInfo: {
      issuingBank: "Barclays Bank PLC",
      advisingBank: "Islami Bank Bangladesh Limited",
      correspondentBank: "Standard Chartered Bank",
      swiftCode: "BARCGB22",
      branch: "London Main Branch",
      accountManager: "James Mitchell",
      managerContact: "james.m@barclays.co.uk",
    },
    shipmentInfo: {
      portOfLoading: "Chittagong Port, Bangladesh",
      portOfDischarge: "Port of London, UK",
      shipmentDate: "2023-12-01",
      lastShipmentDate: "2023-12-10",
      transportType: "Sea Freight",
      shippingCompany: "Mediterranean Shipping Company",
      insurance: "Marine Insurance by Sadharan Bima",
      incoterms: "CIF",
    },
    goodsInfo: [
      {
        productName: "Leather Handbags",
        hsCode: "4202.21.00",
        quantity: 500,
        unit: "PCS",
        unitPrice: 45,
        totalValue: 22500,
        description: "Genuine leather handbags for women",
      },
      {
        productName: "Leather Wallets",
        hsCode: "4202.31.00",
        quantity: 300,
        unit: "PCS",
        unitPrice: 33,
        totalValue: 9900,
        description: "Premium leather wallets for men and women",
      },
    ],
    paymentInfo: {
      terms: "At Sight",
      marginAmount: 6480,
      bankCharges: 200,
      commission: 324,
      dueDate: "2024-01-05",
      status: "Active",
      paidAmount: 0,
      paymentDate: "",
    },
    documentsRequired: [
      "Commercial Invoice",
      "Packing List",
      "Bill of Lading",
      "Insurance Certificate",
      "Certificate of Origin",
      "Quality Certificate",
    ],
    tracking: {
      status: "Production Started",
      remarks:
        "Manufacturing in progress. Expected completion by November 2023.",
      attachments: [
        { name: "LC_Original.pdf", type: "PDF", size: "2.2 MB" },
        { name: "Sample_Approval.pdf", type: "PDF", size: "1.9 MB" },
      ],
      lastUpdated: "2023-09-20 14:15",
    },
  },

  {
    id: 5,
    lcNumber: "LC-2023-005",
    status: "Completed",
    openDate: "18/06/2023",
    dueDate: "18/09/2023",
    products: "Tea, Spices",
    quantity: "3000 kg",
    totalAmount: "$18,750.00",
    beneficiary: "Spice Garden Ltd",

    basicInfo: {
      lcNumber: "LC-2023-005",
      lcType: "Sight LC",
      issueDate: "2023-06-18",
      expiryDate: "2023-09-18",
      lcValue: 18750,
      currency: "USD",
      status: "Completed",
    },
    buyerInfo: {
      name: "Pierre Dubois",
      company: "European Spice Importers",
      address: "456 Spice Avenue, Paris, France",
      contactPerson: "Marie Claire",
      phone: "+33 1 42 86 83 26",
      email: "import@eurospice.fr",
    },
    sellerInfo: {
      name: "Ravi Patel",
      company: "Spice Garden Ltd",
      address: "789 Spice Market, Kerala, India",
      bankName: "Canara Bank",
      accountNumber: "1357924680",
      swiftCode: "CNRBINBBXXX",
      email: "export@spicegarden.in",
    },
    bankInfo: {
      issuingBank: "BNP Paribas",
      advisingBank: "Canara Bank Kerala",
      correspondentBank: "Deutsche Bank",
      swiftCode: "BNPAFRPP",
      branch: "Paris Main Branch",
      accountManager: "Antoine Laurent",
      managerContact: "a.laurent@bnpparibas.com",
    },
    shipmentInfo: {
      portOfLoading: "Cochin Port, India",
      portOfDischarge: "Port of Le Havre, France",
      shipmentDate: "2023-08-15",
      lastShipmentDate: "2023-08-20",
      transportType: "Sea Freight",
      shippingCompany: "Hapag-Lloyd",
      insurance: "Marine Insurance by National Insurance",
      incoterms: "FOB",
    },
    goodsInfo: [
      {
        productName: "Black Tea",
        hsCode: "0902.30.00",
        quantity: 2000,
        unit: "KG",
        unitPrice: 6.5,
        totalValue: 13000,
        description: "Premium grade black tea from Kerala",
      },
      {
        productName: "Mixed Spices",
        hsCode: "0910.99.00",
        quantity: 1000,
        unit: "KG",
        unitPrice: 5.75,
        totalValue: 5750,
        description: "Organic spice mix including cardamom, pepper, cinnamon",
      },
    ],
    paymentInfo: {
      terms: "At Sight",
      marginAmount: 3750,
      bankCharges: 150,
      commission: 188,
      dueDate: "2023-09-18",
      status: "Paid",
      paidAmount: 18750,
      paymentDate: "2023-09-10",
    },
    documentsRequired: [
      "Commercial Invoice",
      "Packing List",
      "Bill of Lading",
      "Insurance Certificate",
      "Certificate of Origin",
      "Phytosanitary Certificate",
      "Organic Certificate",
    ],
    tracking: {
      status: "Completed Successfully",
      remarks:
        "Payment received. Goods delivered successfully. Transaction completed.",
      attachments: [
        { name: "LC_Completed.pdf", type: "PDF", size: "2.0 MB" },
        { name: "Payment_Receipt.pdf", type: "PDF", size: "800 KB" },
        { name: "Delivery_Confirmation.pdf", type: "PDF", size: "1.1 MB" },
      ],
      lastUpdated: "2023-09-18 16:30",
    },
  },

  {
    id: 6,
    lcNumber: "LC-2023-006",
    status: "Under Review",
    openDate: "12/09/2023",
    dueDate: "12/12/2023",
    products: "Pharmaceutical Items",
    quantity: "500 units",
    totalAmount: "$67,890.00",
    beneficiary: "MediCare Pharma",

    basicInfo: {
      lcNumber: "LC-2023-006",
      lcType: "Standby LC",
      issueDate: "2023-09-12",
      expiryDate: "2023-12-12",
      lcValue: 67890,
      currency: "USD",
      status: "Under Review",
    },
    buyerInfo: {
      name: "Dr. Michael Roberts",
      company: "Global Healthcare Solutions",
      address: "321 Medical Plaza, Toronto, Canada",
      contactPerson: "Lisa Anderson",
      phone: "+1 (416) 555-0198",
      email: "procurement@globalhealthcare.ca",
    },
    sellerInfo: {
      name: "Dr. Priya Sharma",
      company: "MediCare Pharma",
      address: "654 Pharma Complex, Hyderabad, India",
      bankName: "HDFC Bank",
      accountNumber: "50100123456789",
      swiftCode: "HDFCINBBXXX",
      email: "export@medicarepharma.in",
    },
    bankInfo: {
      issuingBank: "Royal Bank of Canada",
      advisingBank: "HDFC Bank Hyderabad",
      correspondentBank: "JPMorgan Chase Bank",
      swiftCode: "ROYCCAT2",
      branch: "Toronto Main Branch",
      accountManager: "David Kim",
      managerContact: "d.kim@rbc.ca",
    },
    shipmentInfo: {
      portOfLoading: "Chennai Port, India",
      portOfDischarge: "Port of Toronto, Canada",
      shipmentDate: "2023-11-20",
      lastShipmentDate: "2023-11-30",
      transportType: "Air Freight",
      shippingCompany: "Air India Cargo",
      insurance: "Temperature Controlled Insurance by ICICI Lombard",
      incoterms: "CIP",
    },
    goodsInfo: [
      {
        productName: "Antibiotics",
        hsCode: "3004.20.00",
        quantity: 300,
        unit: "BOXES",
        unitPrice: 156,
        totalValue: 46800,
        description: "FDA approved antibiotic medications",
      },
      {
        productName: "Vaccines",
        hsCode: "3002.20.00",
        quantity: 200,
        unit: "VIALS",
        unitPrice: 105.45,
        totalValue: 21090,
        description: "Temperature-sensitive vaccine storage required",
      },
    ],
    paymentInfo: {
      terms: "30 Days after sight",
      marginAmount: 13578,
      bankCharges: 400,
      commission: 679,
      dueDate: "2023-12-12",
      status: "Under Review",
      paidAmount: 0,
      paymentDate: "",
    },
    documentsRequired: [
      "Commercial Invoice",
      "Packing List",
      "Airway Bill",
      "Insurance Certificate",
      "Certificate of Origin",
      "WHO Certificate",
      "FDA Approval Certificate",
      "Cold Chain Certificate",
    ],
    tracking: {
      status: "Regulatory Review",
      remarks:
        "Under regulatory compliance review. Health Canada approval pending.",
      attachments: [
        { name: "LC_Application.pdf", type: "PDF", size: "3.5 MB" },
        { name: "Regulatory_Docs.pdf", type: "PDF", size: "4.2 MB" },
        { name: "WHO_Certificate.pdf", type: "PDF", size: "1.6 MB" },
        { name: "FDA_Approval.pdf", type: "PDF", size: "2.1 MB" },
      ],
      lastUpdated: "2023-09-28 09:45",
    },
  },
];

export const customers = [
  {
    // Basic Customer Info (from first object)
    id: 1,
    name: "Ahmed Hassan",
    phone: "+880 1712-345678",
    location: "Dhaka, Bangladesh",
    totalPurchased: "$3,250.00",
    lastPurchase: "20 Sep 2023",

    // Detailed Customer Info
    basicInfo: {
      customerId: "CUST-2023-0001",
      name: "Ahmed Hassan",
      type: "Retail",
      status: "Active",
      profilePhoto: null,
      joinDate: "2021-03-12",
      customerTier: "Silver",
    },
    contactInfo: {
      phone: "+880 1712-345678",
      email: "ahmed.hassan@email.com",
      website: null,
      billingAddress: "45 Dhanmondi Road, Dhaka-1205, Bangladesh",
      shippingAddress: "45 Dhanmondi Road, Dhaka-1205, Bangladesh",
      contactPerson: "Ahmed Hassan",
      contactPersonPhone: "+880 1712-345678",
      contactPersonEmail: "ahmed.hassan@email.com",
    },
    businessInfo: {
      companyName: "Hassan Trading",
      businessType: "Local Trader",
      tradeLicense: "TL-BD-456123",
      tin: "TIN-BD-123456789",
      vatInfo: "VAT Registered (BD-456789)",
      creditLimit: 5000,
      paymentTerms: "Cash on Delivery",
      currency: "BDT",
    },
    bankInfo: {
      bankName: "Dutch Bangla Bank",
      branch: "Dhanmondi Branch",
      accountNumber: "********7890",
      routingNumber: "090260456",
      swiftCode: "DBBLBDDHXXX",
      iban: "BD33DBBL1234567890",
    },
    transactionHistory: {
      totalPurchases: 260000,
      outstandingDues: 0,
      advancePaid: 0,
      lastPurchaseDate: "2023-09-20",
      lastPurchaseAmount: 3250,
      totalTransactions: 12,
      averageOrderValue: 2708,
    },
    lcLinks: [
      {
        lcNumber: "LC-2023-001",
        status: "Active",
        value: 45250,
        issueDate: "2023-08-15",
      },
    ],
    documents: [
      {
        name: "Trade_License_BD.pdf",
        type: "PDF",
        size: "1.8 MB",
        uploadDate: "2021-03-15",
      },
      {
        name: "NID_Copy.pdf",
        type: "PDF",
        size: "800 KB",
        uploadDate: "2021-03-12",
      },
    ],
    notes: {
      remarks:
        "Regular customer. Prefers Bengali communication. Usually orders textile items.",
      assignedManager: "Rashid Khan",
      managerContact: "rashid@company.com",
      lastContact: "2023-09-20",
      nextFollowUp: "2023-10-20",
      specialInstructions:
        "Provide local delivery option. Accept mobile banking payments.",
    },
  },

  {
    // Basic Customer Info
    id: 2,
    name: "Sarah Khan",
    phone: "+880 1523-456789",
    location: "Chittagong, Bangladesh",
    totalPurchased: "$1,890.50",
    lastPurchase: "18 Sep 2023",
    status: "Active",

    // Detailed Customer Info
    basicInfo: {
      customerId: "CUST-2023-0002",
      name: "Sarah Khan",
      type: "Wholesale",
      status: "Active",
      profilePhoto: null,
      joinDate: "2022-07-08",
      customerTier: "Bronze",
    },
    contactInfo: {
      phone: "+880 1523-456789",
      email: "sarah.khan@business.com",
      website: "www.sarahenterprises.com",
      billingAddress: "78 Agrabad Commercial Area, Chittagong-4100, Bangladesh",
      shippingAddress:
        "78 Agrabad Commercial Area, Chittagong-4100, Bangladesh",
      contactPerson: "Sarah Khan",
      contactPersonPhone: "+880 1523-456789",
      contactPersonEmail: "sarah.khan@business.com",
    },
    businessInfo: {
      companyName: "Sarah Enterprises",
      businessType: "Import & Export",
      tradeLicense: "TL-CTG-789456",
      tin: "TIN-CTG-987654321",
      vatInfo: "VAT Registered (CTG-123456)",
      creditLimit: 10000,
      paymentTerms: "Net 15 days",
      currency: "USD",
    },
    bankInfo: {
      bankName: "IFIC Bank",
      branch: "Agrabad Branch",
      accountNumber: "********2345",
      routingNumber: "070270123",
      swiftCode: "IFICBDDH",
      iban: "BD47IFIC2345678901",
    },
    transactionHistory: {
      totalPurchases: 151240,
      outstandingDues: 5600,
      advancePaid: 1200,
      lastPurchaseDate: "2023-09-18",
      lastPurchaseAmount: 1890.5,
      totalTransactions: 23,
      averageOrderValue: 1971,
    },
    lcLinks: [
      {
        lcNumber: "LC-2023-002",
        status: "Expired",
        value: 125800,
        issueDate: "2023-07-22",
      },
    ],
    documents: [
      {
        name: "Export_License.pdf",
        type: "PDF",
        size: "2.1 MB",
        uploadDate: "2022-07-10",
      },
      {
        name: "Company_Registration.pdf",
        type: "PDF",
        size: "1.4 MB",
        uploadDate: "2022-07-08",
      },
      {
        name: "Bank_Statement.pdf",
        type: "PDF",
        size: "3.2 MB",
        uploadDate: "2023-01-15",
      },
    ],
    notes: {
      remarks:
        "Growing business. Interested in bulk orders. Good payment history.",
      assignedManager: "Nasir Ahmed",
      managerContact: "nasir@company.com",
      lastContact: "2023-09-18",
      nextFollowUp: "2023-10-15",
      specialInstructions: "Offer volume discounts. Port delivery preferred.",
    },
  },

  {
    // Basic Customer Info
    id: 3,
    name: "Mohammad Ali",
    phone: "+880 1634-567890",
    location: "Sylhet, Bangladesh",
    totalPurchased: "$4,120.75",
    lastPurchase: "12 Sep 2023",
    status: "Inactive",

    // Detailed Customer Info
    basicInfo: {
      customerId: "CUST-2023-0003",
      name: "Mohammad Ali",
      type: "Retail",
      status: "Inactive",
      profilePhoto: null,
      joinDate: "2020-11-22",
      customerTier: "Gold",
    },
    contactInfo: {
      phone: "+880 1634-567890",
      email: "mohammad.ali@gmail.com",
      website: null,
      billingAddress: "234 Zindabazar, Sylhet-3100, Bangladesh",
      shippingAddress: "234 Zindabazar, Sylhet-3100, Bangladesh",
      contactPerson: "Mohammad Ali",
      contactPersonPhone: "+880 1634-567890",
      contactPersonEmail: "mohammad.ali@gmail.com",
    },
    businessInfo: {
      companyName: "Ali Electronics",
      businessType: "Electronics Retailer",
      tradeLicense: "TL-SYL-321654",
      tin: "TIN-SYL-456789123",
      vatInfo: "VAT Registered (SYL-789123)",
      creditLimit: 8000,
      paymentTerms: "Net 30 days",
      currency: "BDT",
    },
    bankInfo: {
      bankName: "Sonali Bank",
      branch: "Sylhet Branch",
      accountNumber: "********3456",
      routingNumber: "050260789",
      swiftCode: "SONBBDDH",
      iban: "BD12SONB3456789012",
    },
    transactionHistory: {
      totalPurchases: 330000,
      outstandingDues: 15000,
      advancePaid: 0,
      lastPurchaseDate: "2023-09-12",
      lastPurchaseAmount: 4120.75,
      totalTransactions: 34,
      averageOrderValue: 2879,
    },
    lcLinks: [
      {
        lcNumber: "LC-2023-003",
        status: "Pending",
        value: 89600,
        issueDate: "2023-09-10",
      },
    ],
    documents: [
      {
        name: "Shop_License.pdf",
        type: "PDF",
        size: "1.2 MB",
        uploadDate: "2020-11-25",
      },
      {
        name: "Tax_Clearance.pdf",
        type: "PDF",
        size: "900 KB",
        uploadDate: "2023-01-10",
      },
    ],
    notes: {
      remarks:
        "Previously regular customer. Payment delays in recent months. Requires follow-up.",
      assignedManager: "Fatima Rahman",
      managerContact: "fatima@company.com",
      lastContact: "2023-09-25",
      nextFollowUp: "2023-10-10",
      specialInstructions:
        "Monitor payment closely. Consider credit limit review.",
    },
  },

  {
    // Basic Customer Info
    id: 4,
    name: "Fatima Rahman",
    phone: "+880 1845-678901",
    location: "Rajshahi, Bangladesh",
    totalPurchased: "$2,675.25",
    lastPurchase: "25 Aug 2023",
    status: "Pending",

    // Detailed Customer Info
    basicInfo: {
      customerId: "CUST-2023-0004",
      name: "Fatima Rahman",
      type: "Wholesale",
      status: "Pending",
      profilePhoto: null,
      joinDate: "2023-08-01",
      customerTier: "Bronze",
    },
    contactInfo: {
      phone: "+880 1845-678901",
      email: "fatima.rahman@textiles.com",
      website: "www.rahmanfabrics.com",
      billingAddress: "567 Silk City, Rajshahi-6000, Bangladesh",
      shippingAddress: "567 Silk City, Rajshahi-6000, Bangladesh",
      contactPerson: "Fatima Rahman",
      contactPersonPhone: "+880 1845-678901",
      contactPersonEmail: "fatima.rahman@textiles.com",
    },
    businessInfo: {
      companyName: "Rahman Fabrics Ltd",
      businessType: "Textile Manufacturer",
      tradeLicense: "TL-RAJ-654987",
      tin: "TIN-RAJ-789456123",
      vatInfo: "VAT Application Pending",
      creditLimit: 3000,
      paymentTerms: "Advance Payment",
      currency: "USD",
    },
    bankInfo: {
      bankName: "Agrani Bank",
      branch: "Rajshahi Branch",
      accountNumber: "********4567",
      routingNumber: "020260456",
      swiftCode: "AGBKBDDH",
      iban: "BD78AGBK4567890123",
    },
    transactionHistory: {
      totalPurchases: 214200,
      outstandingDues: 0,
      advancePaid: 5000,
      lastPurchaseDate: "2023-08-25",
      lastPurchaseAmount: 2675.25,
      totalTransactions: 8,
      averageOrderValue: 3344,
    },
    lcLinks: [
      {
        lcNumber: "LC-2023-004",
        status: "Active",
        value: 32400,
        issueDate: "2023-09-05",
      },
    ],
    documents: [
      {
        name: "Company_Incorporation.pdf",
        type: "PDF",
        size: "2.8 MB",
        uploadDate: "2023-08-02",
      },
      {
        name: "Factory_License.pdf",
        type: "PDF",
        size: "1.7 MB",
        uploadDate: "2023-08-05",
      },
      {
        name: "Environmental_Clearance.pdf",
        type: "PDF",
        size: "2.2 MB",
        uploadDate: "2023-08-08",
      },
    ],
    notes: {
      remarks:
        "New customer with textile manufacturing background. Shows potential for large orders.",
      assignedManager: "Karim Ahmed",
      managerContact: "karim@company.com",
      lastContact: "2023-09-01",
      nextFollowUp: "2023-10-05",
      specialInstructions:
        "Nurture relationship. Offer competitive pricing for bulk orders.",
    },
  },

  {
    // Basic Customer Info
    id: 5,
    name: "Karim Ahmed",
    phone: "+880 1956-789012",
    location: "Khulna, Bangladesh",
    totalPurchased: "$5,450.00",
    lastPurchase: "22 Sep 2023",
    status: "Active",

    // Detailed Customer Info
    basicInfo: {
      customerId: "CUST-2023-0005",
      name: "Karim Ahmed",
      type: "Wholesale",
      status: "Active",
      profilePhoto: null,
      joinDate: "2021-12-15",
      customerTier: "Gold",
    },
    contactInfo: {
      phone: "+880 1956-789012",
      email: "karim@spiceexports.com",
      website: "www.ahmedspices.com",
      billingAddress: "890 Spice Market, Khulna-9000, Bangladesh",
      shippingAddress: "890 Spice Market, Khulna-9000, Bangladesh",
      contactPerson: "Karim Ahmed",
      contactPersonPhone: "+880 1956-789012",
      contactPersonEmail: "karim@spiceexports.com",
    },
    businessInfo: {
      companyName: "Ahmed Spice Exports",
      businessType: "Spice Exporter",
      tradeLicense: "TL-KHU-987321",
      tin: "TIN-KHU-321654987",
      vatInfo: "VAT Registered (KHU-654321)",
      creditLimit: 15000,
      paymentTerms: "Net 45 days",
      currency: "USD",
    },
    bankInfo: {
      bankName: "Pubali Bank",
      branch: "Khulna Branch",
      accountNumber: "********5678",
      routingNumber: "030260123",
      swiftCode: "PUBABDDH",
      iban: "BD56PUBA5678901234",
    },
    transactionHistory: {
      totalPurchases: 436000,
      outstandingDues: 8900,
      advancePaid: 2500,
      lastPurchaseDate: "2023-09-22",
      lastPurchaseAmount: 5450,
      totalTransactions: 28,
      averageOrderValue: 4338,
    },
    lcLinks: [
      {
        lcNumber: "LC-2023-005",
        status: "Completed",
        value: 18750,
        issueDate: "2023-06-18",
      },
      {
        lcNumber: "LC-2022-156",
        status: "Closed",
        value: 65000,
        issueDate: "2022-11-20",
      },
    ],
    documents: [
      {
        name: "Export_Registration.pdf",
        type: "PDF",
        size: "2.5 MB",
        uploadDate: "2021-12-18",
      },
      {
        name: "Organic_Certificate.pdf",
        type: "PDF",
        size: "1.9 MB",
        uploadDate: "2022-03-10",
      },
      {
        name: "Quality_Certificate.pdf",
        type: "PDF",
        size: "1.3 MB",
        uploadDate: "2023-01-20",
      },
    ],
    notes: {
      remarks:
        "Excellent customer with consistent orders. Specializes in organic spices. Very reliable.",
      assignedManager: "Nadia Islam",
      managerContact: "nadia@company.com",
      lastContact: "2023-09-22",
      nextFollowUp: "2023-11-01",
      specialInstructions:
        "VIP treatment. Offer seasonal promotions. Priority shipping available.",
    },
  },

  {
    // Basic Customer Info
    id: 6,
    name: "Nadia Islam",
    phone: "+880 1367-890123",
    location: "Barishal, Bangladesh",
    totalPurchased: "$1,230.75",
    lastPurchase: "10 Sep 2023",
    status: "Pending",

    // Detailed Customer Info
    basicInfo: {
      customerId: "CUST-2023-0006",
      name: "Nadia Islam",
      type: "Retail",
      status: "Pending",
      profilePhoto: null,
      joinDate: "2023-07-20",
      customerTier: "Bronze",
    },
    contactInfo: {
      phone: "+880 1367-890123",
      email: "nadia.islam@healthcare.com",
      website: null,
      billingAddress: "123 Medical Plaza, Barishal-8200, Bangladesh",
      shippingAddress: "123 Medical Plaza, Barishal-8200, Bangladesh",
      contactPerson: "Nadia Islam",
      contactPersonPhone: "+880 1367-890123",
      contactPersonEmail: "nadia.islam@healthcare.com",
    },
    businessInfo: {
      companyName: "Nadia Medical Supplies",
      businessType: "Medical Equipment Distributor",
      tradeLicense: "TL-BAR-456789",
      tin: "TIN-BAR-654321789",
      vatInfo: "VAT Registration Processing",
      creditLimit: 2000,
      paymentTerms: "Cash on Delivery",
      currency: "BDT",
    },
    bankInfo: {
      bankName: "Janata Bank",
      branch: "Barishal Branch",
      accountNumber: "********6789",
      routingNumber: "010260456",
      swiftCode: "JANBBDDH",
      iban: "BD34JANB6789012345",
    },
    transactionHistory: {
      totalPurchases: 98460,
      outstandingDues: 2500,
      advancePaid: 800,
      lastPurchaseDate: "2023-09-10",
      lastPurchaseAmount: 1230.75,
      totalTransactions: 6,
      averageOrderValue: 2051,
    },
    lcLinks: [
      {
        lcNumber: "LC-2023-006",
        status: "Under Review",
        value: 67890,
        issueDate: "2023-09-12",
      },
    ],
    documents: [
      {
        name: "Medical_License.pdf",
        type: "PDF",
        size: "1.8 MB",
        uploadDate: "2023-07-22",
      },
      {
        name: "Drug_License.pdf",
        type: "PDF",
        size: "1.4 MB",
        uploadDate: "2023-07-25",
      },
      {
        name: "Health_Permit.pdf",
        type: "PDF",
        size: "1.1 MB",
        uploadDate: "2023-08-01",
      },
    ],
    notes: {
      remarks:
        "New customer in healthcare sector. Requires regulatory compliance support. Potential for growth.",
      assignedManager: "Dr. Rahman",
      managerContact: "rahman@company.com",
      lastContact: "2023-09-15",
      nextFollowUp: "2023-10-01",
      specialInstructions:
        "Provide regulatory guidance. Ensure all medical equipment meets standards.",
    },
  },
];

export const teamMembers = [
  {
    id: 1,
    name: "Rashid Khan",
    phone: "+880 1712-123456",
    role: "Manager",
    warehouse: "Dhaka, Bangladesh",
  },
  {
    id: 2,
    name: "Fatima Ahmed",
    phone: "+880 1523-234567",
    role: "Warehouse Keeper",
    warehouse: "Chittagong, Bangladesh",
  },
  {
    id: 3,
    name: "Nasir Rahman",
    phone: "+880 1634-345678",
    role: "Accountant",
    warehouse: "Dhaka, Bangladesh",
  },
  {
    id: 4,
    name: "Ayesha Islam",
    phone: "+880 1845-456789",
    role: "Sales Executive",
    warehouse: "Rajshahi, Bangladesh",
  },
  {
    id: 5,
    name: "Karim Hassan",
    phone: "+880 1956-567890",
    role: "Operations Coordinator",
    warehouse: "Khulna, Bangladesh",
  },
  {
    id: 6,
    name: "Nadia Khan",
    phone: "+880 1367-678901",
    role: "Logistics Officer",
    warehouse: "Barishal, Bangladesh",
  },
  {
    id: 7,
    name: "Omar Ali",
    phone: "+880 1478-789012",
    role: "Quality Inspector",
    warehouse: "Comilla, Bangladesh",
  },
  {
    id: 8,
    name: "Zainab Rahman",
    phone: "+880 1589-890123",
    role: "Customs Officer",
    warehouse: "Dhaka, Bangladesh",
  },
  {
    id: 9,
    name: "Mahmud Hasan",
    phone: "+880 1690-901234",
    role: "Warehouse Keeper",
    warehouse: "Chittagong, Bangladesh",
  },
  {
    id: 10,
    name: "Ruma Begum",
    phone: "+880 1701-012345",
    role: "Sales Executive",
    warehouse: "Sylhet, Bangladesh",
  },
];

export   const products = [
    {
      id: 1,
      name: "Mild Steel Rod",
      category: "Steel Rods",
      LCNumber:"234hf3",
      size: "12mm x 12m",
      color: "Silver",
      quantity: 150,
      unit: "pieces",
      unitPrice: "$25.50",
      location: "Warehouse A"
    },
    {
      id: 2,
      name: "Galvanized Steel Sheet",
      category: "Steel Sheets",
      size: "4ft x 8ft x 2mm",
      color: "Silver",
      quantity: 75,
      unit: "sheets",
      unitPrice: "$45.00",
      location: "Warehouse B"
    },
    {
      id: 3,
      name: "Steel Angle Bar",
      category: "Structural Steel",
      size: "50mm x 50mm x 6m",
      color: "Black",
      quantity: 35,
      unit: "pieces",
      unitPrice: "$18.75",
      location: "Warehouse A"
    },
    {
      id: 4,
      name: "Stainless Steel Plate",
      category: "Steel Plates",
      size: "3ft x 6ft x 5mm",
      color: "Silver",
      quantity: 8,
      unit: "plates",
      unitPrice: "$125.00",
      location: "Warehouse C"
    },
    {
      id: 5,
      name: "Steel Pipe",
      category: "Steel Pipes",
      size: "6 inch diameter x 6m",
      color: "Black",
      quantity: 25,
      unit: "pieces",
      unitPrice: "$65.50",
      location: "Warehouse B"
    },
    {
      id: 6,
      name: "Carbon Steel Bar",
      category: "Steel Bars",
      size: "25mm x 6m",
      color: "Dark Gray",
      quantity: 120,
      unit: "pieces",
      unitPrice: "$32.25",
      location: "Warehouse A"
    },
    {
      id: 7,
      name: "Steel H-Beam",
      category: "Structural Steel",
      size: "200mm x 100mm x 12m",
      color: "Gray",
      quantity: 15,
      unit: "pieces",
      unitPrice: "$185.00",
      location: "Warehouse C"
    },
    {
      id: 8,
      name: "Coil Steel Strip",
      category: "Steel Coils",
      size: "50mm width x 1000m",
      color: "Silver",
      quantity: 6,
      unit: "coils",
      unitPrice: "$450.00",
      location: "Warehouse B"
    },
    {
      id: 9,
      name: "Steel Wire Mesh",
      category: "Wire Products",
      size: "4ft x 100ft x 2mm",
      color: "Galvanized",
      quantity: 40,
      unit: "rolls",
      unitPrice: "$75.00",
      location: "Warehouse A"
    },
    {
      id: 10,
      name: "TMT Steel Bar",
      category: "Steel Bars",
      size: "16mm x 12m",
      color: "Brown",
      quantity: 200,
      unit: "pieces",
      unitPrice: "$28.00",
      location: "Warehouse B"
    }
  ];

  export const initialSalesData = [
    {
      id: 1,
      productName: "Mild Steel Rod",
      productId: 1,
      lcNumber: "LC001",
      quantity: 25,
      price: 25.5,
      invoiceStatus: "yes",
      date: "2024-09-21",
      customer: "Rahman Steel Works",
      category: "Steel Rods",
      size: "12mm x 12m",
      unit: "pieces",
    },
    {
      id: 2,
      productName: "Galvanized Steel Sheet",
      productId: 2,
      lcNumber: "LC002",
      quantity: 10,
      price: 45.0,
      invoiceStatus: "yes",
      date: "2024-09-22",
      customer: "Metro Construction",
      category: "Steel Sheets",
      size: "4ft x 8ft x 2mm",
      unit: "sheets",
    },
    {
      id: 3,
      productName: "Steel Angle Bar",
      productId: 3,
      lcNumber: "LC003",
      quantity: 8,
      price: 18.75,
      invoiceStatus: "no",
      date: "2024-09-20",
      customer: "Building Solutions Ltd",
      category: "Structural Steel",
      size: "50mm x 50mm x 6m",
      unit: "pieces",
    },
    {
      id: 4,
      productName: "Stainless Steel Plate",
      productId: 4,
      lcNumber: "LC004",
      quantity: 2,
      price: 125.0,
      invoiceStatus: "pending",
      date: "2024-09-19",
      customer: "Industrial Fabricators",
      category: "Steel Plates",
      size: "3ft x 6ft x 5mm",
      unit: "plates",
    },
    {
      id: 5,
      productName: "Steel Pipe",
      productId: 5,
      lcNumber: "LC005",
      quantity: 5,
      price: 65.5,
      invoiceStatus: "yes",
      date: "2024-09-18",
      customer: "Pipe & Fittings Co",
      category: "Steel Pipes",
      size: "6 inch diameter x 6m",
      unit: "pieces",
    },
    {
      id: 6,
      productName: "Carbon Steel Bar",
      productId: 6,
      lcNumber: "LC006",
      quantity: 15,
      price: 32.25,
      invoiceStatus: "pending",
      date: "2024-09-10",
      customer: "Steel Traders",
      category: "Steel Bars",
      size: "25mm x 6m",
      unit: "pieces",
    },
    {
      id: 7,
      productName: "Steel H-Beam",
      productId: 7,
      lcNumber: "LC007",
      quantity: 3,
      price: 185.0,
      invoiceStatus: "yes",
      date: "2024-08-25",
      customer: "Heavy Construction",
      category: "Structural Steel",
      size: "200mm x 100mm x 12m",
      unit: "pieces",
    },
    {
      id: 8,
      productName: "Coil Steel Strip",
      productId: 8,
      lcNumber: "LC008",
      quantity: 1,
      price: 450.0,
      invoiceStatus: "no",
      date: "2024-08-20",
      customer: "Manufacturing Corp",
      category: "Steel Coils",
      size: "50mm width x 1000m",
      unit: "coils",
    },
    {
      id: 9,
      productName: "Steel Wire Mesh",
      productId: 9,
      lcNumber: "LC009",
      quantity: 8,
      price: 75.0,
      invoiceStatus: "pending",
      date: "2024-09-16",
      customer: "Mesh Solutions",
      category: "Wire Products",
      size: "4ft x 100ft x 2mm",
      unit: "rolls",
    },
    {
      id: 10,
      productName: "TMT Steel Bar",
      productId: 10,
      lcNumber: "LC010",
      quantity: 30,
      price: 28.0,
      invoiceStatus: "yes",
      date: "2024-09-17",
      customer: "Construction Materials Ltd",
      category: "Steel Bars",
      size: "16mm x 12m",
      unit: "pieces",
    },
    {
      id: 11,
      productName: "Mild Steel Rod",
      productId: 1,
      lcNumber: "LC011",
      quantity: 50,
      price: 25.5,
      invoiceStatus: "yes",
      date: "2024-09-15",
      customer: "ABC Construction",
      category: "Steel Rods",
      size: "12mm x 12m",
      unit: "pieces",
    },
    {
      id: 12,
      productName: "Steel Pipe",
      productId: 5,
      lcNumber: "LC012",
      quantity: 12,
      price: 65.5,
      invoiceStatus: "pending",
      date: "2024-09-14",
      customer: "Plumbing Solutions",
      category: "Steel Pipes",
      size: "6 inch diameter x 6m",
      unit: "pieces",
    },
  ];


  export const expensesData= [
      {
        id: 1,
        date: "2025-09-23",
        time: "09:30 AM",
        category: "Transport",
        description: "Fuel for delivery truck",
        amount: 2500,
        paymentMethod: "Cash",
        icon: "Fuel",
      },
      {
        id: 2,
        date: "2025-09-23",
        time: "11:15 AM",
        category: "Transport",
        description: "Driver salary advance",
        amount: 3000,
        paymentMethod: "Cash",
        icon: "Users",
      },
      {
        id: 3,
        date: "2025-09-23",
        time: "02:30 PM",
        category: "Maintenance",
        description: "Truck repair and service",
        amount: 4500,
        paymentMethod: "Bank",
        icon: "Wrench",
      },
      {
        id: 4,
        date: "2025-09-23",
        time: "04:00 PM",
        category: "Office",
        description: "Tea and snacks for workers",
        amount: 800,
        paymentMethod: "Cash",
        icon: "Coffee",
      },
      {
        id: 5,
        date: "2025-09-22",
        time: "10:00 AM",
        category: "Rent",
        description: "Office rent payment",
        amount: 15000,
        paymentMethod: "Bank",
        icon: "Building",
      },
      {
        id: 6,
        date: "2025-09-22",
        time: "03:00 PM",
        category: "Transport",
        description: "New truck tire purchase",
        amount: 8000,
        paymentMethod: "Card",
        icon: "Truck",
      },
    ]
